name: Unit Tests
on:
  workflow_call:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: github-ubuntu-latest-s
    steps:
      - name: checkout action
        uses: actions/checkout@v2
        with:
          path: main
          fetch-depth: 0
      - name: checkout bats-core
        uses: actions/checkout@v2
        with:
          path: bats-core
          repository: bats-core/bats-core
          fetch-depth: 0
      - name: Install BATS test framework
        run:
          sudo ./bats-core/install.sh /usr/local
      - name: Execute BATS tests
        run:
          cd main && bats test/check-quality-gate-test.bats
